### ISSUE TITLE
macs2 call peak error

### ISSUE THREAD

**Issue by VikiyD** [stuart-lab/signac#1331]
Thanks for providing such a great software, I built r object according to the tutorial (https://stuartlab.org/signac/articles/pbmc_vignette.html). Before normalization, I'm trying to call peaks within my dataset with CallPeaks function. However, I got an error below:

```r
peaks <- CallPeaks(pbmc,outdir ="/signac")
```
```r
# insert reproducible example here
INFO  @ Fri, 10 Feb 2023 12:29:52: 
# Command line: callpeak -t fragments.tsv.gz -g 2.7e+09 -f BED --nomodel --extsize 200 --shift -100 -n Ctrl --outdir /signac
# ARGUMENTS LIST:
# name = Ctrl
# format = BED
# ChIP-seq file = ['fragments.tsv.gz']
# control file = None
# effective genome size = 2.70e+09
# band width = 300
# model fold = [5, 50]
# qvalue cutoff = 5.00e-02
# The maximum gap between significant sites is assigned as the read length/tag size.
# The minimum length of peaks is assigned as the predicted fragment length "d".
# Larger dataset will be scaled towards smaller dataset.
# Range for calculating regional lambda is: 10000 bps
# Broad region calling is off
# Paired-End mode is off
 
INFO  @ Fri, 10 Feb 2023 12:29:52: #1 read tag files... 
INFO  @ Fri, 10 Feb 2023 12:29:52: #1 read treatment tags... 
Traceback (most recent call last):
  File "MACS2/IO/Parser.pyx", line 302, in MACS2.IO.Parser.BEDParser.__tlen_parse_line
IndexError: list index out of range
Exception ignored in: 'MACS2.IO.Parser.GenericParser.tsize'
Traceback (most recent call last):
  File "MACS2/IO/Parser.pyx", line 302, in MACS2.IO.Parser.BEDParser.__tlen_parse_line
IndexError: list index out of range
Traceback (most recent call last):
  File "MACS2/IO/Parser.pyx", line 323, in MACS2.IO.Parser.BEDParser.__fw_parse_line
IndexError: list index out of range

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/programs/x86_64-linux/macs/2.2.4/bin/macs2", line 652, in <module>
    main()
  File "/programs/x86_64-linux/macs/2.2.4/bin/macs2", line 51, in main
    run( args )
  File "/programs/x86_64-linux/macs/2.2.4/lib/python3.7/site-packages/MACS2/callpeak_cmd.py", line 65, in run
    else:       (treat, control) = load_tag_files_options  (options)
  File "/programs/x86_64-linux/macs/2.2.4/lib/python3.7/site-packages/MACS2/callpeak_cmd.py", line 391, in load_tag_files_options
    treat = tp.build_fwtrack()
  File "MACS2/IO/Parser.pyx", line 186, in MACS2.IO.Parser.GenericParser.build_fwtrack
  File "MACS2/IO/Parser.pyx", line 201, in MACS2.IO.Parser.GenericParser.build_fwtrack
  File "MACS2/IO/Parser.pyx", line 337, in MACS2.IO.Parser.BEDParser.__fw_parse_line
IndexError: list index out of range
Error in file(file, "rt") : cannot open the connection
In addition: Warning message:
In file(file, "rt") :
  cannot open file 'peaks.narrowPeak': No such file or directory
```

**Comment by valentinaOpazo** [comment]
I got the same error, how do you solve?
