### ISSUE TITLE
Multiple fragment/sample files for CallPeak using system()

### ISSUE THREAD

**Issue by hira-anis** [stuart-lab/signac#1526]
Hey,

I am using https://stuartlab.org/signac/articles/pbmc_multiomic on a multiome dataset. 
I have 5 samples with 5 different fragment files stored in a folder called "Signac_fragpath" ,
Here is my code. I used feedback from different posts tackling the issue with macs2 to counter CallPeak function and the numpy version requirement.

```
system('bash -c "~/opt/anaconda3/bin/macs2 callpeak -t ~/Desktop/ArchR_multiome_signac/Signac_fragpath/ -g 2.7e+09 -f BED --nomodel --extsize 200 --shift -100 -n bloodasc_subset --outdir ~/Desktop/ArchR_multiome_signac"')
#ValueError: numpy.ndarray size changed, may indicate binary incompatibility. Expected 96 from C header, got 88 from PyObject
#upgrading numpy as a rec from bioconductor
# pip install numpy==1.20.0
```
Here is what the object looks like:
An object of class Seurat 
126080 features across 5815 samples within 2 assays 
Active assay: ATAC (89479 features, 0 variable features)
 1 other assay present: RNA

```
Here is the error:

Found 633 cell barcodes
Done Processing 15 million linesFound 1570 cell barcodes
Done Processing 14 million linesFound 1922 cell barcodes
Done Processing 32 million linesFound 1994 cell barcodes
Done Processing 15 million linesFound 456 cell barcodes
Done Processing 11 million linesExtracting TSS positions
Extracting fragments at TSSs

Computing TSS enrichment score
There were 50 or more warnings (use warnings() to see the first 50)
Picking joint bandwidth of 655
Picking joint bandwidth of 1550
Picking joint bandwidth of 0.119
Picking joint bandwidth of 0.0271
Picking joint bandwidth of 0.00029
Picking joint bandwidth of 574
Picking joint bandwidth of 1280
Picking joint bandwidth of 0.118
Picking joint bandwidth of 0.0263
Picking joint bandwidth of 0.000288
INFO  @ Sat, 11 Nov 2023 23:34:37: 
# Command line: callpeak -t ~Desktop/ArchR_multiome_signac/Signac_fragpath/ -g 2.7e+09 -f BED --nomodel --extsize 200 --shift -100 -n bloodasc_subset --outdir /Users/hiraanis/Desktop/ArchR_multiome_signac
# ARGUMENTS LIST:
# name = bloodasc_subset
# format = BED
# ChIP-seq file = ['~/Desktop/ArchR_multiome_signac/Signac_fragpath/']
# control file = None
# effective genome size = 2.70e+09
# band width = 300
# model fold = [5, 50]
# qvalue cutoff = 5.00e-02
# The maximum gap between significant sites is assigned as the read length/tag size.
# The minimum length of peaks is assigned as the predicted fragment length "d".
# Larger dataset will be scaled towards smaller dataset.
# Range for calculating regional lambda is: 10000 bps
# Broad region calling is off
# Paired-End mode is off
 
INFO  @ Sat, 11 Nov 2023 23:34:37: #1 read tag files... 
INFO  @ Sat, 11 Nov 2023 23:34:37: #1 read treatment tags... 
Traceback (most recent call last):
  File "~/opt/anaconda3/bin/macs2", line 653, in <module>
    main()
  File "~/opt/anaconda3/bin/macs2", line 51, in main
    run( args )
  File "~/opt/anaconda3/lib/python3.8/site-packages/MACS2/callpeak_cmd.py", line 65, in run
    else:       (treat, control) = load_tag_files_options  (options)
  File "~/opt/anaconda3/lib/python3.8/site-packages/MACS2/callpeak_cmd.py", line 387, in load_tag_files_options
    tp = options.parser(options.tfile[0], buffer_size=options.buffer_size)
  File "MACS2/IO/Parser.pyx", line 330, in MACS2.IO.Parser.GenericParser.__init__
  **File "~/opt/anaconda3/lib/python3.8/gzip.py", line 58, in open
    binary_file = GzipFile(filename, gz_mode, compresslevel)
  File "~/opt/anaconda3/lib/python3.8/gzip.py", line 173, in __init__
    fileobj = self.myfileobj = builtins.open(filename, mode or 'rb')
IsADirectoryError: [Errno 21] Is a directory: '~/Desktop/ArchR_multiome_signac/Signac_fragpath/'**


```
Please help me troubleshoot the code for a directory with multiple fragment files using system.

Thank you!

**Comment by timoast** [comment]
Please show the full code you're running and the output of `sessionInfo()`

**Comment by timoast** [comment]
@hira-anis any update on this?
